// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTweetInput struct {
	Text string `json:"text"`
}

type CreateUserInput struct {
	Name       string `json:"name"`
	Identifier string `json:"identifier"`
}

type TweetInput struct {
	ID string `json:"id"`
}

type UserInput struct {
	ID string `json:"id"`
}
