version: '3'
services:
  app:
    image: golang:1.13
    container_name: app
    working_dir: /go/src/app
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./app:/go/src/app
    ports:
      - 8080:8080
    tty:
      true

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGPASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    hostname: postgres
    restart: always
    user: root
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/pgsql
    ports:
      - 5432:5432
